CREATE DATABASE TASKS_MANAGER;

USE TASKS_MANAGER;

CREATE TABLE TASK (
	ID INT PRIMARY KEY IDENTITY(1,1),
	[NAME] VARCHAR(150) NOT NULL,
	[DESCRIPTION] VARCHAR(200) NOT NULL,
	[PRIORITY] VARCHAR(50) NOT NULL,
	LIMITDATE DATETIME NOT NULL,
	[STATUS] VARCHAR(50) NOT NULL
);

SELECT * FROM TASK;